### ISSUE TITLE
I got a problem with get 'Keystroke'

### ISSUE THREAD

**Issue by leoppark94** [Selyatin/claves#2]
Hello! Now I'm looking for simple library about collecting keyboard and mouse input.

now I'm testing your library, because it seems light, and got all the features I need.

but I found that keyboard strokes works strange.

now I'm testing on windows.

![image](https://user-images.githubusercontent.com/65339488/237032575-16a2fef5-0087-4a62-8174-e5f60ed59761.png)

F1 ~ F12 came in as a Char('\0')
Backspace key came in as a Delete
Delete key came in as Char('\0')
Insert key came in as Char('\0')
PrintScreen key and Scroll Lock, Pause Key also came in as Char('\0')

But I found some of the keyboard input in your 'claves::Keystroke'

What should I do to fix it?

**Comment by Selyatin** [comment]
You can add the extra cases for non-char buttons [at this line](https://github.com/Selyatin/claves/blob/ef04a86c79e99df98cf97ff675f69085dbe3fcac/src/windows.rs#L97).

Check out [these docs](https://docs.rs/winapi/latest/winapi/um/winuser/index.html) and search for `VK_ ` and you'll see the virtual keys listed one after another, it should be a relatively easy fix.

**Comment by leoppark94** [comment]
Thanks!

**Comment by Selyatin** [comment]
@leoppark94 would you be interested in making a PR to add the extra cases? Other people might find it useful too.

**Comment by leoppark94** [comment]
@Selyatin Sorry for the late answer  I can do it but now thesedays...A little bit busy.

But I also think it could be very useful for a lot of people.

If nobody didn't do the similar work until I have some time.. I'll try it someday !
